"""bigint

Revision ID: 6eee438ff0db
Revises: e7fd7ec22649
Create Date: 2025-07-03 13:57:18.488526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6eee438ff0db'
down_revision: Union[str, Sequence[str], None] = 'e7fd7ec22649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contestant', 'userref',
               existing_type=mysql.VARCHAR(length=18),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('game', 'userid',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user', 'userid',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'userid',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('game', 'userid',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('contestant', 'userref',
               existing_type=sa.BigInteger(),
               type_=mysql.VARCHAR(length=18),
               existing_nullable=True)
    # ### end Alembic commands ###
