"""test

Revision ID: e7fd7ec22649
Revises: 
Create Date: 2025-07-02 17:02:46.674492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e7fd7ec22649'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('name', sa.String(length=50), nullable=False))
    op.alter_column('game', 'userid',
               existing_type=mysql.VARCHAR(length=18),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('user', 'userid',
               existing_type=mysql.VARCHAR(length=18),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'userid',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=18),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('game', 'userid',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=18),
               existing_nullable=False)
    op.drop_column('game', 'name')
    # ### end Alembic commands ###
